// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIP6P8G9xr8q53OSEDI4XaOCn3PDxaft0',
    appId: '1:754023666887:web:87d6b46fa6491ecf275ae2',
    messagingSenderId: '754023666887',
    projectId: 'taverna-ecf6b',
    authDomain: 'taverna-ecf6b.firebaseapp.com',
    storageBucket: 'taverna-ecf6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD15foNTemtVde1abVSklOM77lCi4OQ7jA',
    appId: '1:754023666887:android:cc129f3e9d24b507275ae2',
    messagingSenderId: '754023666887',
    projectId: 'taverna-ecf6b',
    storageBucket: 'taverna-ecf6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnI_m1wPbwjQj_IVFNBaPR5FTs8_CkHWk',
    appId: '1:754023666887:ios:df21b7492772ee34275ae2',
    messagingSenderId: '754023666887',
    projectId: 'taverna-ecf6b',
    storageBucket: 'taverna-ecf6b.appspot.com',
    iosBundleId: 'com.example.taverna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnI_m1wPbwjQj_IVFNBaPR5FTs8_CkHWk',
    appId: '1:754023666887:ios:df21b7492772ee34275ae2',
    messagingSenderId: '754023666887',
    projectId: 'taverna-ecf6b',
    storageBucket: 'taverna-ecf6b.appspot.com',
    iosBundleId: 'com.example.taverna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIP6P8G9xr8q53OSEDI4XaOCn3PDxaft0',
    appId: '1:754023666887:web:c4869617fe15b67d275ae2',
    messagingSenderId: '754023666887',
    projectId: 'taverna-ecf6b',
    authDomain: 'taverna-ecf6b.firebaseapp.com',
    storageBucket: 'taverna-ecf6b.appspot.com',
  );

}